language: go
go:
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
script:
  - go test -v github.com/sfanous/go-feedly/feedly -args -cover "../testdata/covers/cover.gif" -cover "../testdata/covers/cover.jpg" -cover "../testdata/covers/cover.png"
notifications:
  email: change